name: newsoftgrouppp
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.9.25
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - absl-py==2.3.1
    - ccimport==0.4.4
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - cumm==0.8.2
    - fire==0.7.1
    - grpcio==1.76.0
    - idna==3.11
    - importlib-metadata==8.7.0
    - joblib==1.5.2
    - lark==1.3.1
    - laspy==2.6.1
    - markdown==3.9
    - markupsafe==3.0.3
    - mpmath==1.3.0
    - munch==4.0.0
    - ninja==1.13.0
    - numpy==1.26.4
    - packaging==25.0
    - pandas==2.3.3
    - pccm==0.4.16
    - pillow==11.3.0
    - plyfile==1.1.3
    - portalocker==3.2.0
    - protobuf==6.33.1
    - pybind11==3.0.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - requests==2.32.5
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - six==1.17.0
    - spconv==2.3.8
    - sympy==1.14.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.4
    - termcolor==3.1.0
    - threadpoolctl==3.6.0
    - torch==1.11.0+cu113
    - torchvision==0.12.0+cu113
    - tqdm==4.67.1
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - werkzeug==3.1.3
    - zipp==3.23.0
prefix: /root/miniconda3/envs/newsoftgrouppp
