name: newsoftgrouppp
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - absl-py==2.3.1
    - ccimport==0.4.4
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - cumm==0.8.2
    - fire==0.7.1
    - grpcio==1.76.0
    - idna==3.11
    - importlib-metadata==8.7.0
    - joblib==1.5.2
    - lark==1.3.1
    - laspy==2.6.1
    - markdown==3.9
    - markupsafe==3.0.3
    - mpmath==1.3.0
    - munch==4.0.0
    - ninja==1.13.0
    - numpy==1.26.4
    - packaging==25.0
    - pandas==2.3.3
    - pccm==0.4.16
    - pillow==11.3.0
    - plyfile==1.1.3
    - portalocker==3.2.0
    - protobuf==6.33.1
    - pybind11==3.0.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - requests==2.32.5
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - six==1.17.0
    - spconv==2.3.8
    - sympy==1.14.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.4
    - termcolor==3.1.0
    - threadpoolctl==3.6.0
    - torch==1.11.0+cu113
    - torchvision==0.12.0+cu113
    - tqdm==4.67.1
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - werkzeug==3.1.3
    - zipp==3.23.0
prefix: /root/miniconda3/envs/newsoftgrouppp
